---
- name: Automate Web Server Deployment and DB Backup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # System path verified via container bash
    maven_path: "/usr/bin/mvn" 
    db_name: "B-Thou_Thearo-db"
    db_user: "root"
    db_pass: "Hello@123"

  tasks:
    # 1. Clear local modifications and fetch latest commits
    - name: Discard local changes and pull latest from GitHub
      shell: |
        git config --global --add safe.directory {{ app_dir }}
        git reset --hard HEAD
        git pull origin main
      args:
        chdir: "{{ app_dir }}"

    # 2. Build production package without triggering unit tests
    - name: Build project package using Maven
      command: "{{ maven_path }} clean package -DskipTests=true"
      args:
        chdir: "{{ app_dir }}"

# 3. Backup the MySQL Production Database
    - name: Create database backup file
      shell: |
        mysqldump --ssl-mode=DISABLED -h final-mysql-db -u {{ db_user }} -p{{ db_pass }} {{ db_name }} > {{ app_dir }}/backup_{{ db_name }}.sql